# Generated by Django 4.1 on 2022-08-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название')),
                ('stage', models.CharField(blank=True, choices=[('0', '-a'), ('1', 'a'), ('2', 'b'), ('3', 'c')], default='0', max_length=255, null=True, verbose_name='Стадия')),
                ('chapter', models.CharField(max_length=1000, null=True, verbose_name='Раздел')),
                ('subchapter', models.CharField(max_length=1000, null=True, verbose_name='Подраздел')),
                ('part', models.CharField(max_length=1000, null=True, verbose_name='Часть')),
                ('book', models.IntegerField(null=True, verbose_name='Том')),
                ('docfile', models.TextField(verbose_name='Путь до файла')),
                ('version', models.IntegerField(default=1, verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('note_type', models.CharField(choices=[('1', 'a'), ('2', 'b'), ('3', 'c')], default='1', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('docfile', models.FileField(blank=True, upload_to='notes/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название')),
                ('address', models.CharField(max_length=1000, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('1', 'a'), ('2', 'b'), ('3', 'c')], default='1', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('notes', models.ManyToManyField(related_name='projects', to='docs.note', verbose_name='Особые отметки')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
