# Generated by Django 4.1 on 2022-08-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AddField(
            model_name='document',
            name='code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Шифр'),
        ),
        migrations.AlterField(
            model_name='document',
            name='book',
            field=models.IntegerField(blank=True, null=True, verbose_name='Том'),
        ),
        migrations.AlterField(
            model_name='document',
            name='chapter',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='document',
            name='part',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Часть'),
        ),
        migrations.AlterField(
            model_name='document',
            name='stage',
            field=models.CharField(choices=[('0', 'Вне стадии'), ('1', 'Стадия П'), ('2', 'Стадия Р'), ('3', 'c')], default='0', max_length=255, null=True, verbose_name='Стадия'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subchapter',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Подраздел'),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='projects', to='docs.note', verbose_name='Особые отметки'),
        ),
    ]
