# Generated by Django 4.1 on 2022-08-15 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0003_alter_document_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='projects_editor', to=settings.AUTH_USER_MODEL, verbose_name='Редакторы'),
        ),
        migrations.AddField(
            model_name='project',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='projects_viewer', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели'),
        ),
        migrations.AlterField(
            model_name='note',
            name='docfile',
            field=models.FileField(blank=True, upload_to='notes/%Y/%m/%d', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('1', 'От заказчика'), ('2', 'От исполнителя'), ('3', 'От ...')], default='1', max_length=255, verbose_name='Источник заметки'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_owner', to=settings.AUTH_USER_MODEL, verbose_name='Главный'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'a'), ('2', 'b'), ('3', 'c')], default='1', max_length=255, verbose_name='Статус'),
        ),
    ]
