# Generated by Django 4.1 on 2022-08-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_chapter_project_chapters_alter_document_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='docs.note', verbose_name='Особые отметки'),
        ),
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='documents', to='docs.note', verbose_name='Особые отметки'),
        ),
    ]
