# Generated by Django 4.1 on 2022-08-19 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_alter_document_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(verbose_name='Путь до папки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('call_rating', models.IntegerField(default=10, verbose_name='Рейтинг обращений')),
            ],
            options={
                'verbose_name': 'Файлы предпросмотра',
                'verbose_name_plural': 'Файлы предпросмотра',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='preview_folder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document', to='docs.preview', verbose_name='Файлы предпросмотра'),
        ),
    ]
