# Generated by Django 4.0.7 on 2022-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_preview_document_preview_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preview',
            name='call_rating',
            field=models.IntegerField(default=5, verbose_name='Рейтинг обращений'),
        ),
    ]
