version: '3.3'
services:
  backend:
    restart: always
    build:
      context: ../storage
      dockerfile: Dockerfile
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: >
      bash -c '
      python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn storage.wsgi:application --bind 0.0.0.0:8000'
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    container_name: nginx
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
